from __future__ import annotations

from typing import Any

from app.agents.base import BaseAgent, AgentResult
from app.models import ResumeVersion, ApplicationStatus
from app.prompts.builders import build_json_prompt
from app.services.llm_provider import llm_provider
from app.utils.ids import make_id
from app.utils.text import contains_metric, has_action_verb


class CVRewriteAgent(BaseAgent):
    name = "CVRewriteAgent"

    async def run(self, state: dict) -> AgentResult:
        session = state["session"]
        resume = session.structured_resume
        jd_analysis = session.jd_analysis
        cv_analysis = session.cv_analysis
        strategy = session.tailoring_strategy
        assert resume is not None and jd_analysis is not None and cv_analysis is not None and strategy is not None

        expected_schema: dict[str, Any] = {
            "type": "object",
            "required": ["tailored_resume", "change_summary", "unsupported_claim_warnings"],
            "properties": {
                "tailored_resume": {
                    "type": "string",
                    "description": "Markdown CV with sections: Summary, Skills, Projects, Education, optional Experience/Certificates.",
                },
                "change_summary": {"type": "array", "items": {"type": "string"}},
                "unsupported_claim_warnings": {"type": "array", "items": {"type": "string"}},
            },
        }
        system, prompt = build_json_prompt(
            task=(
                "Rewrite the CV for the target JD. Use the original CV as the only source of facts. "
                "Improve wording, ordering, role alignment, and bullet strength. Do not invent metrics, "
                "technologies, employers, degrees, tools, or responsibilities. Do not directly claim any "
                "keyword marked as missing in evidence_map. The output CV should be concise, ATS-friendly, "
                "and suitable for a student/intern/fresher when applicable."
            ),
            schema=expected_schema,
            inputs={
                "company_name": session.company_name,
                "role_title": session.role_title,
                "original_resume_text": session.original_resume_text,
                "structured_resume": resume.model_dump(),
                "job_description_text": session.job_description_text,
                "jd_analysis": jd_analysis.model_dump(),
                "cv_analysis": cv_analysis.model_dump(),
                "tailoring_strategy": strategy.model_dump(),
            },
            skill_names=["resume-tailoring", "jd-analysis", "application-safety"],
        )
        data = await llm_provider.complete_json(prompt, system, max_output_tokens=8192)
        if isinstance(data, dict) and data.get("mock"):
            content, change_summary = _fallback_rewrite(session)
            warnings: list[str] = []
        else:
            content = str(data.get("tailored_resume", "")).strip()
            change_summary = [str(x) for x in data.get("change_summary", [])]
            warnings = [str(x) for x in data.get("unsupported_claim_warnings", [])]
            if not content:
                raise ValueError("LLM returned an empty tailored_resume.")

        version = ResumeVersion(
            version_id=make_id("rv"),
            content=content.strip(),
            change_summary=change_summary or [
                "Generated a JD-tailored CV using LLM prompt and resume-tailoring skill.",
                "Preserved factual boundaries from the original CV.",
            ],
            honesty_report={
                "status": "pending_honesty_review",
                "unsupported_claim_warnings_from_rewriter": warnings,
            },
        )
        session.tailored_resume_versions.append(version)
        session.selected_resume_version_id = version.version_id
        session.status = ApplicationStatus.generated
        return AgentResult(self.name, version.model_dump(), ["Tailored CV generated by LLM."])


def _fallback_rewrite(session) -> tuple[str, list[str]]:
    resume = session.structured_resume
    jd_analysis = session.jd_analysis
    strategy = session.tailoring_strategy
    role_title = session.role_title or jd_analysis.role_focus.get("role_type", "Software Engineering Role")
    supported_keywords = [kw for kw, status in strategy.evidence_map.items() if status == "supported"]
    skill_line = ", ".join(_unique(resume.skills + supported_keywords)) or "Software Engineering fundamentals"
    core = ", ".join(supported_keywords[:5]) if supported_keywords else "software engineering fundamentals"
    summary = (
        f"Software Engineering candidate targeting {role_title}, with verified experience in {core}. "
        f"Focused on practical, maintainable implementation aligned with the role requirements."
    )
    project_bullets = _rewrite_bullets(resume.projects or resume.experience, supported_keywords)
    content = f"# Tailored CV\n\n## Summary\n{summary}\n\n## Skills\n{skill_line}\n\n## Projects\n"
    content += "\n".join(f"- {b}" for b in project_bullets) if project_bullets else "- Add one relevant project bullet based on verified experience from the original CV."
    if resume.experience:
        content += "\n\n## Experience\n" + "\n".join(f"- {b}" for b in resume.experience)
    if resume.education:
        content += "\n\n## Education\n" + "\n".join(f"- {b}" for b in resume.education)
    if resume.certificates:
        content += "\n\n## Certificates\n" + "\n".join(f"- {b}" for b in resume.certificates)
    return content, [
        "Rewrote summary toward the target role.",
        "Prioritized supported JD keywords in Skills.",
        "Excluded unsupported JD keywords from direct CV claims.",
    ]


def _unique(items: list[str]) -> list[str]:
    seen = set()
    out = []
    for item in items:
        normalized = item.strip()
        if normalized and normalized.lower() not in seen:
            seen.add(normalized.lower())
            out.append(normalized)
    return out


def _rewrite_bullets(bullets: list[str], supported_keywords: list[str]) -> list[str]:
    rewritten = []
    for bullet in bullets[:6]:
        clean = bullet.strip(" -•\t")
        if not clean:
            continue
        prefix = "Developed" if not has_action_verb(clean) else ""
        suffix = "" if contains_metric(clean) else " with attention to maintainability, clarity, and role-relevant implementation details"
        rewritten.append(f"{prefix + ' ' if prefix else ''}{clean}{suffix}".strip())
    return rewritten
